# Generated by Django 3.2.13 on 2022-05-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('question1', models.CharField(max_length=20)),
                ('question2', models.BooleanField(default=True)),
                ('question3', models.BooleanField(default=True)),
                ('question4', models.CharField(max_length=30)),
                ('question5', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizzScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(max_length=10)),
            ],
        ),
    ]
