# Generated by Django 3.2.13 on 2022-05-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(null=True)),
                ('link_linkedin', models.URLField(blank=True, max_length=400)),
                ('link_lusofona', models.URLField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='portfolio/static/portfolio/images')),
                ('description', models.TextField(blank=True)),
                ('link_wiki', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_projects', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='portfolio/static/portfolio/images')),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(default=0)),
                ('github', models.TextField(default='')),
                ('participants_in_projects', models.ManyToManyField(default='Alone', to='portfolio.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year', models.IntegerField(default=0)),
                ('etcs', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('programing_languages', models.ManyToManyField(to='portfolio.ProgrammingLanguages')),
                ('projetos', models.ManyToManyField(to='portfolio.Project')),
                ('teacher_p', models.ManyToManyField(related_name='cadeiras', to='portfolio.Person')),
                ('teacher_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Quizz',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/static/portfolio/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
