# Generated by Django 3.2.13 on 2022-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220529_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher_p',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_t',
        ),
        migrations.AddField(
            model_name='subject',
            name='link_lusofona',
            field=models.URLField(default=2, max_length=405),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='portfolio.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_of_projects',
            field=models.CharField(default='', max_length=40),
        ),
    ]
