# Generated by Django 3.2.13 on 2022-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220529_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
