# Generated by Django 3.2.13 on 2022-06-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skills_skill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguages',
            name='image',
            field=models.ImageField(upload_to='portfolio/static/portfolio/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/static/portfolio/images'),
        ),
    ]
