# Generated by Django 3.2.13 on 2022-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220613_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(default='nothing', max_length=10000)),
                ('link_news', models.URLField(max_length=405)),
                ('skill_number', models.IntegerField(default=0)),
            ],
        ),
    ]
